name: Net_Framework48 Integration Pipeline

on:
  push:
    branches:
      - main

env:
  PROJECT_PATH: CI_con_NetFramework_4_8.csproj

jobs:
  build-project:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Restaurar Paquetes Nuget
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          dir
          nuget restore ${{env.PROJECT_PATH}}
      
      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        #run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
        run: msbuild /m /p:Configuration=Release ${{env.PROJECT_PATH}}
