name: Net_Framework48 Integration Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-project:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        
      - name: imprimir cosas
        run: "${{env.PROJECT_PATH}}"

      - name: imprimir cosas 2
        run: "${{env.GITHUB_WORKSPACE}}"

      - name: imprimir cosas 3
        run: "${{env.BUILD_CONFIGURATION}}

      - name: Restaurar Paquetes Nuget
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}
      
      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        #run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
        run: msbuild /m /p:Configuration=Release ${{env.SOLUTION_FILE_PATH}}
